config/routes.rb
Rails.application.routes.draw do
  devise_for :members, controllers: { registrations: 'registrations' }

  resources :posts, only: %i[new create index]

  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :member

  validates :content, presence: true, length: { minimum: 5 }
  validates :member_id, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_member!, except: [:index]

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = current_member.posts.build
  end

  def create
    @post = current_member.posts.build(post_params)

    if @post.save
      redirect_to root_path, notice: 'Post was successfully created'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <nav class="navbar">
      <p><%= link_to "*_Members Only_*", root_path %></p>
      <p><%= link_to "Post", new_post_path %></p>
      <% if member_signed_in? %>
        <p><%= link_to current_member.name, edit_member_registration_path  %></p>
        <p><%= link_to "Log Out", destroy_member_session_path, method: :delete %></p>
      <% else %>
        <p> <%= link_to "Log In", new_member_session_path %></p>
        <p><%= link_to "Sign Up", new_member_registration_path %></p>
      <% end %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class="posts-container">
  <% @posts.each do |post| %>
    <div class="post">
      <% if member_signed_in? %>
        <strong><%= post.member.name %>:</strong> <br>
      <% end %>
      <%= post.content %>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<section class="form-container">
  <h3>Create a new post</h3>
  <%= form_with model: @post do |form| %>
  <%= form.label :content, class: 'hidden' %> <br>
  <%= form.text_area :content, size: '60x20', placeholder: "What's on your mind?", autofocus: true %> <br><br>
  <%= form.submit "Post" %>
  <% end %>
</section>